apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
      {{- include "sonarr.labels" . | nindent 4 }}
data:
  PGID: {{ .Values.uid }}
  PUID: {{ .Values.gid }}
  TZ: {{ .Values.timezone }}
  UMASK: {{ .Values.umask }}